### ISSUE TITLE
Looking for "X-BambooHR-Error-Messsage" with 3 's's

### ISSUE THREAD

**Issue by jbubriski** [BambooHR/bhr-api-php#14]
In the sample PHP code the header for error messages is `X-BambooHR-Error-Messsage`.  Note that there are 3 's's in the word "Messsage".  Is this intentional?  Or should it be spelled correctly?

**Comment by jbubriski** [comment]
This recent update page mentions the header with the correct spelling: https://help.bamboohr.com/hc/en-us/articles/115007466507-API-Endpoint-Change-5-19-2017-

**Comment by jbubriski** [comment]
Also, I can not find any mention of that header anywhere in the documentation.  Maybe it should be added there for further clarification.

**Comment by jlesueur** [comment]
Hi the three s's are due to a typo that existed early in the API's lifetime. We have since added a correctly spelled header, but both the old and new exist. Since there is a safe migration path, updating this library would be a good idea.

I didn't realize we never referenced this header in the documentation. I'll put that in as something to add.
